workspace(name = "test")

local_repository(
    name = "com_github_johnynek_bazel_jar_jar",
    path = "../",
)

load(
    "@com_github_johnynek_bazel_jar_jar//:jar_jar.bzl",
    "jar_jar_repositories",
)

jar_jar_repositories()

load(
    "//:deps.bzl",
    "deps",
)

deps()

register_toolchains("//jar_jar_aspect:jar_jar_toolchain")
