workspace(name = "test")

load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")


local_repository(name = "com_github_johnynek_bazel_jar_jar",
                 path = "../")

load(
    "@com_github_johnynek_bazel_jar_jar//:jar_jar.bzl",
    "jar_jar_repositories"
)


jvm_maven_import_external(
  name = "com_twitter_scalding_args",
  artifact = "com.twitter:scalding-args_2.9.3:0.12.0",
  server_urls = ["https://repo.maven.apache.org/maven2"],
  artifact_sha256 = "2869f65981e57b34e25eb46e3dd2dda170ee7db7cdce04db3c7bf3d53c75084b",
)

jar_jar_repositories()
