workspace(name = "test_aspect")

load("@bazel_tools//tools/build_defs/repo:jvm.bzl", "jvm_maven_import_external")

local_repository(
    name = "com_github_johnynek_bazel_jar_jar",
    path = "../",
)

load(
    "@com_github_johnynek_bazel_jar_jar//:jar_jar.bzl",
    "jar_jar_repositories",
)

jvm_maven_import_external(
    name = "org_twitter4j_twitter4j_core",
    artifact = "org.twitter4j:twitter4j-core:4.0.7",
    artifact_sha256 = "f3d28049f1c13752c2ea71397fdcda8d9723cf315e7101502997fddfe9aad66d",
    server_urls = ["https://repo.maven.apache.org/maven2"],
)

jar_jar_repositories()

register_toolchains("//:jar_jar_toolchain")
