name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build_test_main:
    name: Build and test (main repository)
    runs_on: ${{ matrix.os }}
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: bazelisk build //...

      - name: Test
        run: bazelisk test //...

  build_test_test:
    name: Build and test (test repository)
    runs_on: ${{ matrix.os }}
    matrix:
      os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Build
        working-directory: test
        run: bazelisk build //...

      - name: Test
        working-directory: test
        run: bazelisk test //...
