name: Test

on:
  push:
  pull_request:

jobs:

  build_test_main:
    name: Build and test main repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Build
        run: bazelisk build //...

      - name: Test
        run: bazelisk test --test_output=errors //...

  build_test:
    name: Build test repository
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8

      - name: Build
        working-directory: test
        run: bazelisk build //...
